name: Build & Push Docker image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: m324demoacrqba.azurecr.io
  IMAGE_NAME: mini-notes-backend

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: ACR

    steps:
      # Step 1: Checkout du dépôt
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest -f ./Dockerfile .

      # Step 3: Login à Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 4: Tag & Push de l'image vers ACR
      - name: Push Docker image to ACR
        run: |
          docker tag $IMAGE_NAME:latest $ACR_LOGIN_SERVER/axelle_$IMAGE_NAME:latest
          docker push $ACR_LOGIN_SERVER/axelle_$IMAGE_NAME:latest
